/**
 * =============================================================================
 * Chapter 04 - Embeddings & Semantic Similarity
 * =============================================================================
 *
 * Description:
 * -----------------------------------------------------------------------------
 * This chapter demonstrates how to generate vector embeddings using the
 * OpenAI Embeddings API and compare those vectors using mathematical
 * similarity algorithms.
 *
 * Embeddings allow machines to understand the semantic meaning of text
 * instead of performing simple keyword matching.
 *
 * This chapter introduces:
 *
 * • OpenAI Embedding Model
 * • Vector Representation
 * • Dot Product
 * • Cosine Similarity
 * • Semantic Search
 *
 * =============================================================================
 *
 * High Level Workflow
 *
 *          sample.json
 *                │
 *                ▼
 *       Read User Documents
 *                │
 *                ▼
 *     Generate OpenAI Embeddings
 *                │
 *                ▼
 *      Store Embedding Vectors
 *                │
 *                ▼
 *      Compare Vector Similarity
 *                │
 *                ▼
 *     Rank Similar Documents
 *
 * =============================================================================
 */

import { OpenAI } from 'openai';
import { configDotenv } from 'dotenv';

import { readFileSync } from 'fs';
import { writeFile } from 'fs/promises';

import { join } from 'path';

/**
 * -----------------------------------------------------------------------------
 * Load Environment Variables
 * -----------------------------------------------------------------------------
 *
 * Reads variables from the `.env` file and makes them available through
 * `process.env`.
 *
 * Required:
 *
 * OPEN_AI_API_KEY=<your_api_key>
 *
 * Without this function, `process.env.OPEN_AI_API_KEY`
 * will be undefined.
 * -----------------------------------------------------------------------------
 */
configDotenv();

/**
 * -----------------------------------------------------------------------------
 * OpenAI Client
 * -----------------------------------------------------------------------------
 *
 * The OpenAI client is responsible for communicating with
 * OpenAI's REST API.
 *
 * Every embedding request is sent through this client.
 *
 * Authentication is performed automatically using the provided API key.
 * -----------------------------------------------------------------------------
 */
const openai = new OpenAI({
    apiKey: process.env.OPEN_AI_API_KEY,
});

/**
 * -----------------------------------------------------------------------------
 * User Type
 * -----------------------------------------------------------------------------
 *
 * Represents one document (or user) in our dataset.
 *
 * Initially every object contains:
 *
 * id
 * category
 * title
 * content
 *
 * After generating embeddings, a new property called
 * `embedded` is added.
 *
 * Example:
 *
 * {
 *    id: "1",
 *    category: "Programming",
 *    title: "Node.js",
 *    content: "...",
 *    embedded: [0.123, -0.422, ...]
 * }
 *
 * -----------------------------------------------------------------------------
 */
type UserT = {

    /**
     * Unique identifier.
     */
    id: string;

    /**
     * Category to which the document belongs.
     */
    category: string;

    /**
     * Short title.
     */
    title: string;

    /**
     * Original text.
     *
     * This text is sent to the Embedding API.
     */
    content: string;

    /**
     * Numerical representation generated by
     * the embedding model.
     *
     * It contains hundreds or thousands of floating
     * point values depending on the selected model.
     *
     * Example:
     *
     * [
     *   0.123,
     *   -0.551,
     *   0.919,
     *   ...
     * ]
     */
    embedded?: number[] | undefined;
};

/**
 * =============================================================================
 * Vector Mathematics
 * =============================================================================
 *
 * Before comparing two documents, we first compare their vectors.
 *
 * Example
 *
 * "I love dogs."
 *
 * ▼
 *
 * [0.24, 0.88, -0.52, ...]
 *
 *
 * "I like puppies."
 *
 * ▼
 *
 * [0.23, 0.86, -0.49, ...]
 *
 * These vectors are mathematically compared using:
 *
 * • Dot Product
 * • Cosine Similarity
 *
 * =============================================================================
 */

/**
 * -----------------------------------------------------------------------------
 * Dot Product
 * -----------------------------------------------------------------------------
 *
 * Calculates the dot product of two vectors.
 *
 * Mathematical Formula
 *
 * A • B =
 *
 * A₁B₁ +
 * A₂B₂ +
 * A₃B₃ +
 * ...
 * AₙBₙ
 *
 * Example
 *
 * Vector A
 *
 * [2,3]
 *
 * Vector B
 *
 * [4,5]
 *
 * Result
 *
 * (2×4) + (3×5)
 *
 * =
 *
 * 23
 *
 * -----------------------------------------------------------------------------
 *
 * Why do we need it?
 *
 * Dot Product tells us how much two vectors point
 * in the same direction.
 *
 * It is also used internally when calculating
 * Cosine Similarity.
 *
 * -----------------------------------------------------------------------------
 *
 * @param vectorA First Vector
 * @param vectorB Second Vector
 *
 * @returns Dot Product
 * -----------------------------------------------------------------------------
 */
const dotProduct = (
    vectorA: number[],
    vectorB: number[]
): number => {

    /**
     * Multiply corresponding values.
     *
     * Example
     *
     * [1,2,3]
     *
     * [4,5,6]
     *
     * ↓
     *
     * (1×4)
     * +
     * (2×5)
     * +
     * (3×6)
     */
    return vectorA.reduce((sum, value, index) => {

        /**
         * Current multiplication result.
         */
        const product = value * vectorB[index]!;

        /**
         * Add current product to running total.
         */
        return sum + product;

    }, 0);

};

/**
 * -----------------------------------------------------------------------------
 * Cosine Similarity
 * -----------------------------------------------------------------------------
 *
 * Calculates how semantically similar two vectors are.
 *
 * Formula
 *
 *              A • B
 * --------------------------------
 * |A| × |B|
 *
 * Where
 *
 * A • B
 *
 * is the Dot Product.
 *
 * |A|
 *
 * is the magnitude (length) of vector A.
 *
 * |B|
 *
 * is the magnitude of vector B.
 *
 * -----------------------------------------------------------------------------
 *
 * Result Range
 *
 * 1.0
 *     Perfect Match
 *
 * 0
 *     No Relationship
 *
 * -1
 *     Opposite Direction
 *
 * -----------------------------------------------------------------------------
 *
 * In embedding models,
 * values are usually between
 *
 * 0.6 → Related
 * 0.8 → Very Similar
 * 0.9+ → Nearly Identical
 *
 * -----------------------------------------------------------------------------
 *
 * @param vectorA First Embedding Vector
 * @param vectorB Second Embedding Vector
 *
 * @returns Cosine Similarity Score
 * -----------------------------------------------------------------------------
 */
const cosineSimilarity = (
    vectorA: number[],
    vectorB: number[]
): number => {

    /**
     * ---------------------------------------------------------
     * Step 1
     *
     * Calculate Dot Product
     * ---------------------------------------------------------
     */
    const dotPr = dotProduct(vectorA, vectorB);

    /**
     * ---------------------------------------------------------
     * Step 2
     *
     * Calculate Magnitude of Vector A
     *
     * |A|
     * ---------------------------------------------------------
     */
    const magnitudeA = Math.sqrt(
        dotProduct(vectorA, vectorA)
    );

    /**
     * ---------------------------------------------------------
     * Step 3
     *
     * Calculate Magnitude of Vector B
     *
     * |B|
     * ---------------------------------------------------------
     */
    const magnitudeB = Math.sqrt(
        dotProduct(vectorB, vectorB)
    );

    /**
     * ---------------------------------------------------------
     * Step 4
     *
     * Calculate Cosine Similarity
     * ---------------------------------------------------------
     */
    return dotPr / (magnitudeA * magnitudeB);

};

/**
 * =============================================================================
 * End of Part 1
 * =============================================================================
 *
 * Next Part
 *
 * • similarity()
 * • getSampleData()
 * • saveDataToJSONFile()
 * • getEmbeddingFromAI()
 *
 * =============================================================================
 */

/**
 * =============================================================================
 * Similarity Engine
 * =============================================================================
 *
 * This section is responsible for comparing embedding vectors.
 *
 * Every document is compared with the selected target document.
 *
 * The comparison process consists of:
 *
 * Target Document
 *        │
 *        ▼
 * Compare With Every Other Document
 *        │
 *        ▼
 * Calculate Dot Product
 *        │
 *        ▼
 * Calculate Cosine Similarity
 *        │
 *        ▼
 * Sort by Highest Similarity
 *        │
 *        ▼
 * Save Results
 *
 * =============================================================================
 */

/**
 * Compares one target document against every other document.
 *
 * The function calculates:
 *
 * • Dot Product
 * • Cosine Similarity
 *
 * After comparison,
 * all documents are sorted in descending order of similarity.
 *
 * @param users Complete dataset.
 * @param targetUser Document used as reference.
 *
 * @returns Ranked list of similar users.
 */
async function similarity(
    users: UserT[] | undefined,
    targetUser: UserT
) {

    /**
     * Safety check.
     *
     * If no users are available,
     * there is nothing to compare.
     */
    if (!users?.length) {
        return null;
    }

    /**
     * Compare every document except the target itself.
     */
    const similarUsers = users

        /**
         * Ignore self comparison.
         *
         * Comparing a vector with itself
         * always produces
         *
         * Cosine Similarity = 1
         */
        .filter((user) => user.id !== targetUser.id)

        /**
         * Transform each user into
         * a similarity object.
         */
        .map((user) => {

            /**
             * Calculate mathematical similarity.
             */
            return {

                /**
                 * Document identifier.
                 */
                name: user.id,

                /**
                 * Raw Dot Product score.
                 */
                dotProduct: dotProduct(
                    user.embedded!,
                    targetUser.embedded!
                ),

                /**
                 * Normalized similarity score.
                 *
                 * This value is generally
                 * preferred over Dot Product.
                 */
                cosine: cosineSimilarity(
                    user.embedded!,
                    targetUser.embedded!
                )

            };

        })

        /**
         * Highest similarity first.
         */
        .sort((a, b) => b.cosine - a.cosine);

    /**
     * Save similarity results.
     *
     * This file is useful for
     *
     * • Debugging
     * • Visualization
     * • Analysis
     */
    await saveDataToJSONFile(
        "finalOutput.json",
        similarUsers
    );

    return similarUsers;
}

/**
 * =============================================================================
 * File Utilities
 * =============================================================================
 *
 * These helper functions are responsible for
 *
 * • Reading JSON
 * • Writing JSON
 *
 * Keeping file operations separate makes
 * the code cleaner and easier to maintain.
 *
 * =============================================================================
 */

/**
 * Reads sample data from disk.
 *
 * File:
 *
 * sample.json
 *
 * The JSON file acts as a small dataset
 * for learning embeddings.
 *
 * Example:
 *
 * [
 *   {
 *      id,
 *      title,
 *      content
 *   }
 * ]
 *
 * @returns Array of users/documents.
 */
async function getSampleData(): Promise<UserT[]> {

    /**
     * Build an absolute path.
     *
     * join() works correctly across
     * Windows, Linux and macOS.
     */
    const filePath = join(
        __dirname,
        "sample.json"
    );

    /**
     * Read file synchronously.
     */
    const fileContent = readFileSync(
        filePath,
        "utf8"
    );

    /**
     * Convert JSON string
     * into JavaScript object.
     */
    return JSON.parse(fileContent);

}

/**
 * Writes any object to disk.
 *
 * Useful for:
 *
 * • Debugging
 * • Inspecting API responses
 * • Saving embeddings
 * • Saving similarity rankings
 *
 * @param fileName Output filename.
 * @param data Data to write.
 */
async function saveDataToJSONFile(
    fileName: string,
    data: unknown
): Promise<void> {

    /**
     * Construct output path.
     */
    const outputPath = join(
        __dirname,
        fileName
    );

    /**
     * Convert object into
     * formatted JSON.
     *
     * null
     *
     * means default replacer.
     *
     * 2
     *
     * means pretty print using
     * two spaces.
     */
    await writeFile(
        outputPath,
        JSON.stringify(data, null, 2),
        "utf8"
    );

}

/**
 * =============================================================================
 * Embedding Service
 * =============================================================================
 *
 * Responsible for communicating
 * with OpenAI's Embedding API.
 *
 * Input
 *
 * [
 *   "Text A",
 *   "Text B",
 *   "Text C"
 * ]
 *
 * ↓
 *
 * OpenAI
 *
 * ↓
 *
 * [
 *   Vector A,
 *   Vector B,
 *   Vector C
 * ]
 *
 * =============================================================================
 */

/**
 * Generates embeddings for multiple documents.
 *
 * Every input string produces
 * one embedding vector.
 *
 * Example
 *
 * Input:
 *
 * [
 *   "Hello",
 *   "Node.js"
 * ]
 *
 * Output:
 *
 * [
 *   [0.12, 0.55, ...],
 *   [-0.22, 0.81, ...]
 * ]
 *
 * @param content Array of text.
 *
 * @returns Embedding response.
 */
async function getEmbeddingFromAI(
    content: string[]
) {

    /**
     * Send all documents
     * to the embedding model.
     *
     * The API generates one
     * embedding for each string.
     */
    const response =
        await openai.embeddings.create({

            /**
             * Embedding model.
             *
             * Optimized for
             * semantic search.
             */
            model: "text-embedding-3-small",

            /**
             * Array of text
             * to convert into vectors.
             */
            input: content

        });

    /**
     * Save the raw API response.
     *
     * Useful for understanding
     * the response structure.
     */
    await saveDataToJSONFile(
        "embedded.json",
        response
    );

    return response;

}

/**
 * =============================================================================
 * End of Part 2
 * =============================================================================
 *
 * Next Part
 *
 * • run()
 * • Generate embeddings
 * • Attach vectors
 * • Similarity ranking
 * • Save output
 * • Complete execution flow
 *
 * =============================================================================
 */

/**
 * =============================================================================
 * Application Entry Point
 * =============================================================================
 *
 * The `run()` function orchestrates the complete embedding pipeline.
 *
 * High-Level Workflow:
 *
 *  Read Sample Data
 *          │
 *          ▼
 *  Extract Text Content
 *          │
 *          ▼
 *  Generate Embeddings
 *          │
 *          ▼
 *  Attach Embeddings
 *          │
 *          ▼
 *  Save Updated Dataset
 *          │
 *          ▼
 *  Compare Similarity
 *          │
 *          ▼
 *  Display Results
 *
 * =============================================================================
 */

/**
 * Executes the complete embedding workflow.
 *
 * Responsibilities:
 *
 * 1. Read sample data.
 * 2. Extract text from every document.
 * 3. Generate embeddings using OpenAI.
 * 4. Attach embeddings to each document.
 * 5. Save the enriched dataset.
 * 6. Compare document similarity.
 * 7. Print the ranked results.
 */
async function run(): Promise<void> {

    console.log("========================================");
    console.log("Chapter 04 - Embeddings");
    console.log("========================================\n");

    /**
     * -------------------------------------------------------------------------
     * Step 1
     *
     * Load sample data.
     * -------------------------------------------------------------------------
     *
     * Reads the sample JSON file containing
     * user/documents.
     *
     * Example:
     *
     * [
     *   {
     *      id,
     *      title,
     *      content
     *   }
     * ]
     */
    const sampleData = await getSampleData();

    console.log(`Loaded ${sampleData.length} documents.\n`);

    /**
     * -------------------------------------------------------------------------
     * Step 2
     *
     * Extract only the content.
     * -------------------------------------------------------------------------
     *
     * The Embedding API only requires text.
     *
     * Therefore we create a simple array
     * containing only the document contents.
     *
     * Example:
     *
     * [
     *   "Node.js is awesome",
     *   "TypeScript improves JavaScript",
     *   ...
     * ]
     */
    const contents = sampleData.map(
        document => document.content
    );

    /**
     * -------------------------------------------------------------------------
     * Step 3
     *
     * Generate Embeddings.
     * -------------------------------------------------------------------------
     *
     * Every string is converted into
     * a high-dimensional numerical vector.
     *
     * Input
     *
     * Text
     *
     * ↓
     *
     * Embedding API
     *
     * ↓
     *
     * Vector
     */
    console.log("Generating embeddings...\n");

    const embeddingResponse =
        await getEmbeddingFromAI(contents);

    /**
     * -------------------------------------------------------------------------
     * Step 4
     *
     * Attach embeddings.
     * -------------------------------------------------------------------------
     *
     * The OpenAI API returns embeddings separately.
     *
     * Here we merge each embedding back
     * into its corresponding document.
     */
    const usersWithEmbeddings = sampleData.map(
        (user, index) => {

            return {

                /**
                 * Preserve existing fields.
                 */
                ...user,

                /**
                 * Attach generated embedding.
                 */
                embedded:
                    embeddingResponse.data[index]?.embedding

            };

        }
    );

    /**
     * -------------------------------------------------------------------------
     * Step 5
     *
     * Save the enriched dataset.
     * -------------------------------------------------------------------------
     *
     * Output:
     *
     * User_data_with_embedded.json
     *
     * This file contains both the original
     * data and the generated embeddings.
     */
    await saveDataToJSONFile(
        "User_data_with_embedded.json",
        usersWithEmbeddings
    );

    console.log("Embeddings generated successfully.\n");

    /**
     * -------------------------------------------------------------------------
     * Step 6
     *
     * Similarity Search.
     * -------------------------------------------------------------------------
     *
     * Compare the first document
     * against every other document.
     *
     * Similarity is calculated using:
     *
     * • Dot Product
     * • Cosine Similarity
     */
    console.log("Calculating similarity...\n");

    const similarUsers =
        await similarity(
            usersWithEmbeddings,
            usersWithEmbeddings[0]!
        );

    /**
     * -------------------------------------------------------------------------
     * Step 7
     *
     * Display Results.
     * -------------------------------------------------------------------------
     *
     * Prints the similarity ranking.
     */
    console.log("========================================");
    console.log("Similarity Results");
    console.log("========================================");

    console.table(similarUsers);

    console.log("\nProcess Completed Successfully.");
}

/**
 * =============================================================================
 * Program Entry Point
 * =============================================================================
 *
 * Every Node.js application begins execution here.
 *
 * Calling `run()` starts the complete
 * embedding generation workflow.
 *
 * =============================================================================
 */
run();